apiVersion: ate.dev/v1alpha1
kind: SandboxConfig
metadata:
  name: gvisor-homelab
spec:
  sandboxClass: gvisor
  default: true
  assets:
    amd64:
      runsc:
        url: "https://storage.googleapis.com/gvisor/releases/nightly/2026-05-19/x86_64/runsc"
        sha256: "a397be1abc2420d26bce6c70e6e2ff96c73aaaab929756c56f5e2089ea842b63"
